apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.actions.skiperator.kartverket.no_Application: |
    discovery.lua: |
      actions = {}
      actions["Suspend"] = {
        ["disabled"] = false,
        ["iconClass"] = "fa fa-fw fa-pause"
      }
      actions["Resume"] = {
        ["disabled"] = false,
        ["iconClass"] = "fa fa-fw fa-play"
      }

      if obj.spec.replicas == 0 then
        actions["Suspend"]["disabled"] = true
      else
        actions["Resume"]["disabled"] = true
      end

      return actions
    definitions:
    - name: Suspend
      action.lua: |
        obj.spec.replicas = 0
        if obj.metadata.annotations == nil then
          obj.metadata.annotations = {["skip.kartverket.no/k8sReplicaLimits"] = "ignore"}
        else
          obj.metadata.annotations["skip.kartverket.no/k8sReplicaLimits"] = "ignore"
        end
        return obj
    - name: Resume
      action.lua: |
        obj.metadata.annotations["skip.kartverket.no/k8sReplicaLimits"] = nil
        obj.spec.replicas = nil
        return obj
