apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.useOpenLibs.skiperator.kartverket.no_Application: "true"
  resource.customizations.actions.skiperator.kartverket.no_Application: |
    discovery.lua: |
      actions = {}
      actions["Suspend"] = {
        ["disabled"] = false,
        ["iconClass"] = "fa fa-fw fa-pause"
      }
      actions["Resume"] = {
        ["disabled"] = false,
        ["iconClass"] = "fa fa-fw fa-play"
      }

      if obj.spec.replicas == 0 then
        actions["Suspend"]["disabled"] = true
      else
        actions["Resume"]["disabled"] = true
      end

      return actions
    definitions:
    - name: Suspend
      action.lua: |
        local json = require("json")
        local last_replicas = json.encode(obj.spec.replicas)
        obj.spec.replicas = 0
        if obj.metadata.annotations == nil then
          obj.metadata.annotations = {
            ["skip.kartverket.no/k8sReplicaLimits"] = "ignore",
            ["skip.kartverket.no/lastReplicas"] = last_replicas
          }
        else
          obj.metadata.annotations["skip.kartverket.no/k8sReplicaLimits"] = "ignore"
          obj.metadata.annotations["skip.kartverket.no/lastReplicas"] = last_replicas
        end
        return obj
    - name: Resume
      action.lua: |
        local json = require("json")
        local last_replicas = obj.spec.annotations["skip.kartverket.no/lastReplicas"]
        obj.metadata.annotations["skip.kartverket.no/k8sReplicaLimits"] = nil

        if last_replicas ~= nil
          obj.spec.replicas = json.decode(last_replicas)
        else
          obj.spec.replicas = nil
        end
        return obj
