apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.actions.skiperator.kartverket.no_Application: |
    discovery.lua: |
      actions = {}
      actions["scale_down"] = {["disabled"] = true}
      actions["scale_up"] = {["disabled"] = true}

      local scale_down = false
      if obj.spec.replicas ~= 0 then
        scale_down = obj.spec.scale_down
      end
      if scale_down then
        actions["scale_down"]["disabled"] = false
      else
        actions["scale_up"]["disabled"] = false
      end

      return actions
    definitions:
    - name: scale_down
      action.lua: |
        obj.spec.replicas = 0
        return obj
